[project]
name = "FortiDynaSync"
version = "0.0.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "requests>=2.32.3",
    "typing>=3.10.0.0",
]
